# Generated by Django 4.2.4 on 2023-09-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('LG', 'LEHENGA'), ('JL', 'JEWELLERY'), ('GP', 'GENTS PANT'), ('BK', 'BORKA'), ('EL', 'ELETRONICS'), ('SH', 'SHOES'), ('CL', 'CLOTHING'), ('SA', 'SAREE')], max_length=2),
        ),
    ]
